name: Workflow
on: 
    push:
        branches: [ "main" ]
jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Run scripts in server
          uses: appleboy/ssh-actions@master
          with:
            key: ${{ secrets.SSH_KEY }}
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            script: |
                cd ${{ vars.project_path }}/${{ github.event.repository.name }}
                git pull origin main